# Generated by Django 5.2.3 on 2025-07-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConversion',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tool', models.CharField(choices=[('LIBREOFFICE', 'LibreOffice'), ('PDF2DOCX', 'PDF to DOCX')], max_length=40)),
                ('operation', models.CharField(choices=[('CONVERT', 'Convert')], default='CONVERT', max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='files.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
