# Generated by Django 5.2.3 on 2025-06-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionTask',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('algorithm', models.CharField(choices=[('DEFLATE', 'Deflate')], max_length=10)),
                ('operation', models.CharField(choices=[('COMPRESS', 'Compress')], max_length=10)),
                ('compressed_size', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
