# Generated by Django 5.2.3 on 2025-07-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressiontask',
            name='algorithm',
            field=models.CharField(choices=[('GHOSTSCRIPT', 'Ghostscript (PDF compression)'), ('MOZJPEG', 'MozJPEG (JPEG compression)'), ('OPTIPNG', 'OptiPNG (PNG compression)'), ('H264', 'H.264 / FFmpeg (Video compression)'), ('AAC', 'AAC / FFmpeg (Audio compression)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='compressiontask',
            name='operation',
            field=models.CharField(choices=[('COMPRESS', 'Compress')], max_length=40),
        ),
    ]
