# Generated by Django 5.2.3 on 2025-07-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0003_alter_compressiontask_algorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressiontask',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
